Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network = "private_network", ip: "192.168.2.50"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.synced_folder = ".", "/vagrant", type: "nfs"
  
  config.vm.provision "shell", path: "provision.sh" 


end
